# Generated by Django 4.2.11 on 2024-05-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=512, null=True)),
                ('office_address', models.CharField(blank=True, max_length=512, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=512, null=True)),
                ('pan', models.CharField(blank=True, max_length=512, null=True)),
                ('passport', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
